name: slash
description: Slash is a simple wallpaper app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  dart_code_metrics: ^5.7.2

flutter:
  uses-material-design: true
