name: slash
description: Slash is a simple wallpaper app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  dio: ^5.2.1+1
  auto_route: ^7.7.0
  url_strategy: ^0.2.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  stream_transform: ^2.1.0
  bloc_concurrency: ^0.2.2
  mocktail: ^0.3.0
  flutter_staggered_grid_view: ^0.6.2
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  golden_toolkit: ^0.15.0
  flutter_cache_manager: ^3.3.1
  path_provider: ^2.0.15
  image_gallery_saver: ^2.0.3
  path: ^1.8.3
  url_launcher: ^6.1.12
  hive: ^2.2.3
  hive_flutter:

dependency_overrides:
  meta: ^1.9.1
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  dart_code_metrics: ^5.7.2
  auto_route_generator: ^7.2.0
  test:
  hive_generator:

flutter:
  uses-material-design: true

  assets:
    - assets/empty.webp
    - assets/error.webp
